### ISSUE TITLE
TypeError when nothing is found on in a document

### ISSUE THREAD

**Issue by oholter** [NorskRegnesentral/skweak#8]
Hi!
I'm getting an exception from fit_and_aggregate. 
```TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'.```
The exception is from line 227 in ```aggregation.py```, ```np.apply_along_axis(...)```

This seems to happen when all of my labeling functions return empty on one of the docs so the DataFrame is empty.

**Comment by plison** [comment]
Are you running the latest version of the toolkit? It seems the same issue as #3 , which I thought I had fixed.

**Comment by oholter** [comment]
I am running v0.2.9 (installed via pip a few days ago)

**Comment by plison** [comment]
My bad, it seemed the last fix was not included in the PyPI package. It should now be fixed, just do `pip install --upgrade skweak` to get the latest version.

**Comment by oholter** [comment]
Hi thanks!
It fixed the above exception. But I got another one. It seems to be related to the same issue (nothing is found).

```
Traceback (most recent call last):
  File "/runner.py", line 105, in <module>
    hmm.fit_and_aggregate(docs)
  File "/venv/lib/python3.8/site-packages/skweak/aggregation.py", line 304, in fit_and_aggregate
    return list(self.pipe(docs))
  File "/venv/lib/python3.8/site-packages/skweak/base.py", line 33, in pipe
    yield self(doc)
  File "/venv/lib/python3.8/site-packages/skweak/aggregation.py", line 296, in __call__
    return super(HMM, self).__call__(doc)
  File "/venv/lib/python3.8/site-packages/skweak/aggregation.py", line 64, in __call__
    agg_df = self._aggregate(df)
  File "/venv/lib/python3.8/site-packages/skweak/aggregation.py", line 326, in _aggregate
    _, forward_lattice = self._do_forward_pass(framelogprob)
  File "/venv/lib/python3.8/site-packages/hmmlearn/base.py", line 501, in _do_forward_pass
    n_samples, n_components = framelogprob.shape
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by plison** [comment]
OK, it should now be fixed. I had tested for the absence of "spans" in a document, but apparently not for documents with spans assigned to empty lists -- sorry about that. Let me know if you still experience problems!

**Comment by oholter** [comment]
Thanks! it works now!
